# config/config.yaml
scale: 8
params:
  regime: 'forcing_no_t_dep'
  Lx: 6.283185307179586  # 2 * math.pi
  Ly: 6.283185307179586  # 2 * math.pi
  Nx: 240
  Ny: 240
  dt: 0.0008  # (1.0E-4) * scale
  mu: 0.02
  nu: 1.025E-5
  t0: 0.0
  nv: 1
  B: 0
  device: "cuda"
  topography: True
  seed: 20240605
integration:
  solver: 'rk4'
  rtol: 1e-4
  atol: 1e-4
  step_size: 1e-4
  adjoint: True
  autonomous: False
data:
  natl_dataset: '/DATASET/NATL/natl_gf_w_5nadirs.nc'
  qg_model_dataset: '../data/forcing_no_t_dep_qg_sol_240_dt=0.0008_save_freq=250_tf=751.nc'
training:
  t0: 10
  dT: 10
  NIter: 40
  alpha_obs: 1.0
  alpha_dyn: 1.0
  delta: 0.1
